framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: kocal/limitless-tcg-stats

        # Redis provider for cache pools
        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            # Dedicated cache pool for Limitless TCG API
            limitless.cache:
                adapter: cache.adapter.redis
