framework:
    http_client:
        scoped_clients:
            limitless.client:
                base_uri: 'https://play.limitlesstcg.com/api/'
                headers:
                    Accept: 'application/json'
                retry_failed:
                    max_retries: 5
                    delay: 1500
                    multiplier: 3
                    max_delay: 30000
